spring:
  application:
    name: usuario
  datasource:
    url: jdbc:postgresql://localhost:5432/usuario
    username: ADMIN
    password: ADMIN
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect