version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-usuario
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: ADMIN
      POSTGRES_PASSWORD: ADMIN
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: